const drinksCollection = [
    {
      id: 'CF001',
      name: 'Espresso Bliss',
      price: '4€',
      descENG: 'White rum<br>Pineapple juice<br>Lime juice<br>Simple syrup<br>Crushed ice<br>Mint leaves (for garnish)<br>Pineapple slice (for garnish)',
      descRUS: 'Белый ром<br>Ананасовый сок<br>Сок лайма<br>Сахарный сироп<br>Дроблёный лёд<br>Листья мяты (для украшения)<br>Кусочек ананаса (для украшения)',
      descUKR: 'Білий ром<br>Ананасовий сік<br>Сік лайма<br>Цукровий сироп<br>Дроблений лід<br>Листя м’яти (для прикраси)<br>Шматочок ананаса (для прикраси)',
      descTUR: 'Beyaz rom<br>Ananas suyu<br>Lime suyu<br>Şeker şurubu<br>Kırık buz<br>Süslemek için nane yaprakları<br>Süslemek için ananas dilimi',
      descSRB: 'Beli rum<br>Sok od ananasa<br>Sok od limete<br>Šećerni sirup<br>Drobljeni led<br>Listići nane (za dekoraciju)<br>Kriška ananasa (za dekoraciju)',
      descKAZ: 'Ақ ром<br>Ананас шырыны<br>Лайм шырыны<br>Қант сиробы<br>Ұнтақталған мұз<br>Жалбыз жапырақтары (безендіру үшін)<br>Ананас тілімі (безендіру үшін)',
      image: '../data/drinksImages/Coffee 1.png',
      isTop: true, 
    },
    {
      id: 'CC001',
      name: 'Tropical Breeze',
      price: '5€',
      descENG: 'Freshly brewed espresso<br>Vanilla syrup<br>Chocolate syrup<br>Steamed milk<br>Whipped cream<br>Chocolate shavings (for garnish)',
      descRUS: 'Свежезаваренный эспрессо<br>Ванильный сироп<br>Шоколадный сироп<br>Пропаренное молоко<br>Взбитые сливки<br>Шоколадная стружка (для украшения)',
      descUKR: 'Свіжозаварений еспресо<br>Ванільний сироп<br>Шоколадний сироп<br>Пропарене молоко<br>Збиті вершки<br>Шоколадна стружка (для прикраси)',
      descTUR: 'Taze demlenmiş espresso<br>Vanilya şurubu<br>Çikolata şurubu<br>Buharda ısıtılmış süt<br>Krem şanti<br>Süslemek için çikolata rendesi',
      descSRB: 'Sveže pripremljen espresso<br>Vanilin sirup<br>Čokoladni sirup<br>Pareno mleko<br>Šlag<br>Rendana čokolada (za dekoraciju)',
      descKAZ: 'Жаңа қайнатылған эспрессо<br>Ваниль сиробы<br>Шоколад сиробы<br>Буға қыздырылған сүт<br>Кілегей<br>Шоколад үгіндісі (безендіру үшін)',
      image: '../data/drinksImages/Coffee 2.png',
      isTop: true, 
    },
    {
      id: 'CC001',
      name: 'Tropical Breeze',
      price: '5€',
      descENG: 'Freshly brewed espresso<br>Vanilla syrup<br>Chocolate syrup<br>Steamed milk<br>Whipped cream<br>Chocolate shavings (for garnish)',
      descRUS: 'Свежезаваренный эспрессо<br>Ванильный сироп<br>Шоколадный сироп<br>Пропаренное молоко<br>Взбитые сливки<br>Шоколадная стружка (для украшения)',
      descUKR: 'Свіжозаварений еспресо<br>Ванільний сироп<br>Шоколадний сироп<br>Пропарене молоко<br>Збиті вершки<br>Шоколадна стружка (для прикраси)',
      descTUR: 'Taze demlenmiş espresso<br>Vanilya şurubu<br>Çikolata şurubu<br>Buharda ısıtılmış süt<br>Krem şanti<br>Süslemek için çikolata rendesi',
      descSRB: 'Sveže pripremljen espresso<br>Vanilin sirup<br>Čokoladni sirup<br>Pareno mleko<br>Šlag<br>Rendana čokolada (za dekoraciju)',
      descKAZ: 'Жаңа қайнатылған эспрессо<br>Ваниль сиробы<br>Шоколад сиробы<br>Буға қыздырылған сүт<br>Кілегей<br>Шоколад үгіндісі (безендіру үшін)',
      image: '../data/drinksImages/Coffee 2.png',
      isTop: true, 
    },
    {
      id: 'CC001',
      name: 'Tropical Breeze',
      price: '5€',
      descENG: 'Freshly brewed espresso<br>Vanilla syrup<br>Chocolate syrup<br>Steamed milk<br>Whipped cream<br>Chocolate shavings (for garnish)',
      descRUS: 'Свежезаваренный эспрессо<br>Ванильный сироп<br>Шоколадный сироп<br>Пропаренное молоко<br>Взбитые сливки<br>Шоколадная стружка (для украшения)',
      descUKR: 'Свіжозаварений еспресо<br>Ванільний сироп<br>Шоколадний сироп<br>Пропарене молоко<br>Збиті вершки<br>Шоколадна стружка (для прикраси)',
      descTUR: 'Taze demlenmiş espresso<br>Vanilya şurubu<br>Çikolata şurubu<br>Buharda ısıtılmış süt<br>Krem şanti<br>Süslemek için çikolata rendesi',
      descSRB: 'Sveže pripremljen espresso<br>Vanilin sirup<br>Čokoladni sirup<br>Pareno mleko<br>Šlag<br>Rendana čokolada (za dekoraciju)',
      descKAZ: 'Жаңа қайнатылған эспрессо<br>Ваниль сиробы<br>Шоколад сиробы<br>Буға қыздырылған сүт<br>Кілегей<br>Шоколад үгіндісі (безендіру үшін)',
      image: '../data/drinksImages/Coffee 2.png',
      isTop: true, 
    },
    {
      id: 'CC001',
      name: 'Tropical Breeze',
      price: '5€',
      descENG: 'Freshly brewed espresso<br>Vanilla syrup<br>Chocolate syrup<br>Steamed milk<br>Whipped cream<br>Chocolate shavings (for garnish)',
      descRUS: 'Свежезаваренный эспрессо<br>Ванильный сироп<br>Шоколадный сироп<br>Пропаренное молоко<br>Взбитые сливки<br>Шоколадная стружка (для украшения)',
      descUKR: 'Свіжозаварений еспресо<br>Ванільний сироп<br>Шоколадний сироп<br>Пропарене молоко<br>Збиті вершки<br>Шоколадна стружка (для прикраси)',
      descTUR: 'Taze demlenmiş espresso<br>Vanilya şurubu<br>Çikolata şurubu<br>Buharda ısıtılmış süt<br>Krem şanti<br>Süslemek için çikolata rendesi',
      descSRB: 'Sveže pripremljen espresso<br>Vanilin sirup<br>Čokoladni sirup<br>Pareno mleko<br>Šlag<br>Rendana čokolada (za dekoraciju)',
      descKAZ: 'Жаңа қайнатылған эспрессо<br>Ваниль сиробы<br>Шоколад сиробы<br>Буға қыздырылған сүт<br>Кілегей<br>Шоколад үгіндісі (безендіру үшін)',
      image: '../data/drinksImages/Coffee 2.png',
      isTop: true, 
    },
    {
      id: 'CC001',
      name: 'Tropical Breeze',
      price: '5€',
      descENG: 'Freshly brewed espresso<br>Vanilla syrup<br>Chocolate syrup<br>Steamed milk<br>Whipped cream<br>Chocolate shavings (for garnish)',
      descRUS: 'Свежезаваренный эспрессо<br>Ванильный сироп<br>Шоколадный сироп<br>Пропаренное молоко<br>Взбитые сливки<br>Шоколадная стружка (для украшения)',
      descUKR: 'Свіжозаварений еспресо<br>Ванільний сироп<br>Шоколадний сироп<br>Пропарене молоко<br>Збиті вершки<br>Шоколадна стружка (для прикраси)',
      descTUR: 'Taze demlenmiş espresso<br>Vanilya şurubu<br>Çikolata şurubu<br>Buharda ısıtılmış süt<br>Krem şanti<br>Süslemek için çikolata rendesi',
      descSRB: 'Sveže pripremljen espresso<br>Vanilin sirup<br>Čokoladni sirup<br>Pareno mleko<br>Šlag<br>Rendana čokolada (za dekoraciju)',
      descKAZ: 'Жаңа қайнатылған эспрессо<br>Ваниль сиробы<br>Шоколад сиробы<br>Буға қыздырылған сүт<br>Кілегей<br>Шоколад үгіндісі (безендіру үшін)',
      image: '../data/drinksImages/Coffee 2.png',
      isTop: true, 
    },
    {
      id: 'CC001',
      name: 'Tropical Breeze',
      price: '5€',
      descENG: 'Freshly brewed espresso<br>Vanilla syrup<br>Chocolate syrup<br>Steamed milk<br>Whipped cream<br>Chocolate shavings (for garnish)',
      descRUS: 'Свежезаваренный эспрессо<br>Ванильный сироп<br>Шоколадный сироп<br>Пропаренное молоко<br>Взбитые сливки<br>Шоколадная стружка (для украшения)',
      descUKR: 'Свіжозаварений еспресо<br>Ванільний сироп<br>Шоколадний сироп<br>Пропарене молоко<br>Збиті вершки<br>Шоколадна стружка (для прикраси)',
      descTUR: 'Taze demlenmiş espresso<br>Vanilya şurubu<br>Çikolata şurubu<br>Buharda ısıtılmış süt<br>Krem şanti<br>Süslemek için çikolata rendesi',
      descSRB: 'Sveže pripremljen espresso<br>Vanilin sirup<br>Čokoladni sirup<br>Pareno mleko<br>Šlag<br>Rendana čokolada (za dekoraciju)',
      descKAZ: 'Жаңа қайнатылған эспрессо<br>Ваниль сиробы<br>Шоколад сиробы<br>Буға қыздырылған сүт<br>Кілегей<br>Шоколад үгіндісі (безендіру үшін)',
      image: '../data/drinksImages/Coffee 2.png',
      isTop: true, 
    },
    {
      id: 'CC001',
      name: 'Tropical Breeze',
      price: '5€',
      descENG: 'Freshly brewed espresso<br>Vanilla syrup<br>Chocolate syrup<br>Steamed milk<br>Whipped cream<br>Chocolate shavings (for garnish)',
      descRUS: 'Свежезаваренный эспрессо<br>Ванильный сироп<br>Шоколадный сироп<br>Пропаренное молоко<br>Взбитые сливки<br>Шоколадная стружка (для украшения)',
      descUKR: 'Свіжозаварений еспресо<br>Ванільний сироп<br>Шоколадний сироп<br>Пропарене молоко<br>Збиті вершки<br>Шоколадна стружка (для прикраси)',
      descTUR: 'Taze demlenmiş espresso<br>Vanilya şurubu<br>Çikolata şurubu<br>Buharda ısıtılmış süt<br>Krem şanti<br>Süslemek için çikolata rendesi',
      descSRB: 'Sveže pripremljen espresso<br>Vanilin sirup<br>Čokoladni sirup<br>Pareno mleko<br>Šlag<br>Rendana čokolada (za dekoraciju)',
      descKAZ: 'Жаңа қайнатылған эспрессо<br>Ваниль сиробы<br>Шоколад сиробы<br>Буға қыздырылған сүт<br>Кілегей<br>Шоколад үгіндісі (безендіру үшін)',
      image: '../data/drinksImages/Coffee 2.png',
      isTop: true, 
    },
    {
      id: 'CC001',
      name: 'Tropical Breeze',
      price: '5€',
      descENG: 'Freshly brewed espresso<br>Vanilla syrup<br>Chocolate syrup<br>Steamed milk<br>Whipped cream<br>Chocolate shavings (for garnish)',
      descRUS: 'Свежезаваренный эспрессо<br>Ванильный сироп<br>Шоколадный сироп<br>Пропаренное молоко<br>Взбитые сливки<br>Шоколадная стружка (для украшения)',
      descUKR: 'Свіжозаварений еспресо<br>Ванільний сироп<br>Шоколадний сироп<br>Пропарене молоко<br>Збиті вершки<br>Шоколадна стружка (для прикраси)',
      descTUR: 'Taze demlenmiş espresso<br>Vanilya şurubu<br>Çikolata şurubu<br>Buharda ısıtılmış süt<br>Krem şanti<br>Süslemek için çikolata rendesi',
      descSRB: 'Sveže pripremljen espresso<br>Vanilin sirup<br>Čokoladni sirup<br>Pareno mleko<br>Šlag<br>Rendana čokolada (za dekoraciju)',
      descKAZ: 'Жаңа қайнатылған эспрессо<br>Ваниль сиробы<br>Шоколад сиробы<br>Буға қыздырылған сүт<br>Кілегей<br>Шоколад үгіндісі (безендіру үшін)',
      image: '../data/drinksImages/Coffee 2.png',
      isTop: true, 
    },
    // добавляй больше напитков по мере необходимости
];


  

export default drinksCollection;
  